### ISSUE TITLE
Invisible reCaptcha break form processing

### ISSUE THREAD

**Issue by onigunn** [evoWeb/recaptcha#25]
Using `ext:form` on TYPO3 8.7.22 with recaptcha version 8.3.0 changing to invisible mode breaks form submission.

I've using for development google provided test keys, so reCaptcha always validates. Submitting a simple test form with reCaptcha set to invisible results in no submission of the form. The `onRecaptchaSubmit` is invoked, seems like validation of the form takes place and then you are redirected back to the form without any errors or something. Seems like that finishers are not processed at all.

Switching back to "normal" mode everything works fine.

TypoScript Constants
```
plugin.tx_recaptcha {
  include_invisible_recaptcha_callback = 1
  invisible_recaptcha_formname = recaptchatest
  enforceCaptcha = 1
  public_key = 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
  private_key = 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
}
```

Simple Test Form
```
renderingOptions:
  submitButtonLabel: Submit
  useInvisibleRecaptcha: true
identifier: recaptchatest
label: 'recaptcha test'
type: Form
prototypeName: standard
finishers:
  -
    options:
      pageUid: '1'
      additionalParameters: ''
    identifier: Redirect
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    identifier: page-1
    label: 'Contact Form'
    type: Page
    renderables:
      -
        defaultValue: ''
        identifier: name
        label: Name
        type: Text
        properties:
          fluidAdditionalAttributes:
            placeholder: Name
        validators:
          -
            identifier: NotEmpty
      -
        defaultValue: ''
        identifier: subject
        label: Subject
        type: Text
        properties:
          fluidAdditionalAttributes:
            placeholder: Subject
        validators:
          -
            identifier: NotEmpty
      -
        defaultValue: ''
        identifier: email
        label: Email
        type: Text
        properties:
          fluidAdditionalAttributes:
            placeholder: 'Email address'
        validators:
          -
            identifier: NotEmpty
          -
            identifier: EmailAddress
      -
        defaultValue: ''
        identifier: message
        label: Message
        type: Textarea
        properties:
          fluidAdditionalAttributes:
            placeholder: ''
        validators:
          -
            identifier: NotEmpty
      -
        renderingOptions:
          submitButtonLabel: true
        type: Recaptcha
        identifier: recaptcha-1
        label: reCAPTCHA
        validators:
          -
            identifier: Recaptcha
```

**Comment by garbast** [comment]
Habe mir das Problem in einer 9er Instanz angeschaut. Das Problem da ist, dass die Formular id immer mit der Uid des Plugins ergänzt wird. Deshalb habe ich in der 9er Version das jetzt gefixt. Schau mal bitte ob der Fix auch in der 8.7 hilft

page.jsInline.1508480348393 {
    value = function onRecaptchaSubmit() { document.querySelectorAll('[data-callback="onRecaptchaSubmit"]')[0].form.submit(); return false; }
    if.isTrue = {$plugin.tx_recaptcha.include_invisible_recaptcha_callback}
}

**Comment by garbast** [comment]
Changing the finisher to
```
finishers:
  -
    options:
      subject: 'Contactform on dev8'
      recipientAddress: test@test.local
      recipientName: ''
      senderAddress: website@test.local
      senderName: ''
      replyToAddress: ''
      carbonCopyAddress: ''
      blindCarbonCopyAddress: ''
      format: html
      attachUploads: true
      translation:
        language: ''
    identifier: EmailToReceiver
  -
    options:
      pageUid: '3'
      additionalParameters: ''
    identifier: Redirect
```
I get an email and redirected to page 3
