### ISSUE TITLE
Finishers are ignored with use of invisible recaptcha

### ISSUE THREAD

**Issue by dahaupt** [evoWeb/recaptcha#7]
**First of all, thanks for your great work building this extension!** 

I have a simple contact form with multiple finishers defined, but even if I use just one it is not executed if I enable invisible recaptcha.

```yaml
finishers:
  -
    options:
      pageUid: '16'
      additionalParameters: ''
    identifier: Redirect
```

If I use the standard visible reCAPTCHA everything is working fine and my finishers are executed (except the already mentioned bug in #6)

Did anybody else noticed this behavior? I'm thankful for any help.
