### ISSUE TITLE
Mail finishers show recaptcha code in mail - v12 

### ISSUE THREAD

**Issue by stigfaerch** [evoWeb/recaptcha#74]
The reason is that in v12 they changed the templateName to 'Default' instead of 'Html'.
To keep compatibility with v11, I think you should just include Default.html and Default.txt templates.

**Comment by bogdan-s0** [comment]
Is there any solution for this?
Emails are triggered as spam because of reCAPTCHA code on email body

**Comment by stigfaerch** [comment]
@bogdan-s0 
As a quickfix, you can add the Default.html and Default.txt templates yourself in your own extensions.
Typoscript:
```
plugin.tx_form {
    settings {
        yamlConfigurations {
            100 = EXT:yourextension/Configuration/Yaml/CustomFormSetup.yaml
        }
    }
}
```
CustomFormSetup.yaml:
```
prototypes:
  standard:
    finishersDefinition:
      EmailToSender:
        options:
          templateRootPaths:
            1975: 'EXT:yourextension/Resources/Private/Extensions/Form/Frontend/Templates/Finishers/Email/'
      EmailToReceiver:
        options:
          templateRootPaths:
            1975: 'EXT:yourextension/Resources/Private/Extensions/Form/Frontend/Templates/Finishers/Email/'
```
Just copy the html.yaml file to your template path.
If you need the txt version, you would have to copy the one from the EXT:form extension and add the if condition yourself.
